test_that("require that a package contains odin files", {
  path <- withr::local_tempdir()
  test_pkg_setup(path)
  expect_error(
    odin_package(path),
    "Did not find any odin code in 'inst/odin'")
})


test_that("require that dust files that exist were plausibly generated by us", {
  path <- withr::local_tempdir()
  test_pkg_setup(path)
  dir.create(file.path(path, "inst/dust"), FALSE, TRUE)
  file.create(file.path(path, "inst/odin/a.R"))
  file.create(file.path(path, "inst/dust/a.cpp"))
  err1 <- expect_error(
    odin_package(path, quiet = TRUE),
    "Refusing to overwrite file not generated by odin2")
  expect_match(conditionMessage(err1),
               "'inst/dust/a.cpp' looks hand-written")

  file.create(file.path(path, "inst/odin/b.R"))
  writeLines(
    "// Generated by odin2 - do not edit",
    file.path(path, "inst/dust/b.cpp"))

  err2 <- expect_error(
    odin_package(path, quiet = TRUE),
    "Refusing to overwrite file not generated by odin2")
  expect_equal(conditionMessage(err2), conditionMessage(err1))

  file.create(file.path(path, "inst/odin/c.R"))
  writeLines(
    "// anything else, really",
    file.path(path, "inst/dust/c.cpp"))

  err3 <- expect_error(
    odin_package(path, quiet = TRUE),
    "Refusing to overwrite file not generated by odin2")
  expect_match(conditionMessage(err3),
               "'inst/dust/a.cpp' and 'inst/dust/c.cpp' look hand-written")
})


test_that("can generate trivial package", {
  path <- withr::local_tempdir()
  test_pkg_setup(path)
  writeLines(c("initial(x) <- 0",
               "update(x) <- 0"),
             file.path(path, "inst/odin/a.R"))
  res <- evaluate_promise(odin_package(path))
  expect_match(res$messages[[1]], "Found 1 odin code file in 'inst/odin'")
})


test_that("can generate trivial package, quietly", {
  path <- withr::local_tempdir()
  test_pkg_setup(path)
  writeLines(c("initial(x) <- 0",
               "update(x) <- 0"),
             file.path(path, "inst/odin/a.R"))
  res <- evaluate_promise(odin_package(path, quiet = TRUE))
  expect_equal(res$messages, character())
})


test_that("clean hyphens from class names", {
  path <- withr::local_tempdir()
  test_pkg_setup(path)
  writeLines(c("initial(x) <- 0",
               "update(x) <- 0"),
             file.path(path, "inst/odin/a-b-c.R"))
  res <- evaluate_promise(odin_package(path, quiet = TRUE))
  expect_equal(res$messages, character())

  expect_true(file.exists(file.path(path, "src/a-b-c.cpp")))
  cpp <- readLines(file.path(path, "src/a-b-c.cpp"))
  expect_match(cpp, "class a_b_c {", fixed = TRUE, all = FALSE)
  expect_match(cpp, "// [[dust2::class(a_b_c)]]", fixed = TRUE, all = FALSE)

  expect_true(file.exists(file.path(path, "R/dust.R")))
  r <- readLines(file.path(path, "R/dust.R"))
  expect_match(r, "a_b_c <- function() {", fixed = TRUE, all = FALSE)
  expect_match(r, 'dust_system_generator("a_b_c",', fixed = TRUE, all = FALSE)
})
