INDEX <- c("i", "j", "k", "l", "i5", "i6", "i7", "i8")

## TODO: it would be great if monty could advertise what is in its
## maths library.
##
## TODO: %% and %/% for monty
FUNCTIONS_MONTY_MATH <-
  c("^" = "pow",
    "%%" = "fmod",
    "%/%" = "fintdiv",
    min = "min",
    max = "max",
    ceiling = "ceil",
    sign = "sign",
    floor = "floor",
    round = "round",
    trunc = "trunc",
    sqrt = "sqrt",
    abs = "abs",
    exp = "exp",
    expm1 = "expm1",
    log = "log",
    log2 = "log2",
    log10 = "log10",
    log1p = "log1p",
    cos = "cos",
    sin = "sin",
    tan = "tan",
    acos = "acos",
    asin = "asin",
    atan = "atan",
    atan2 = "atan2",
    cosh = "cosh",
    sinh = "sinh",
    tanh = "tanh",
    acosh = "acosh",
    asinh = "asinh",
    atanh = "atanh")


FUNCTIONS <- list(
  "+" = 1:2,
  "-" = 1:2,
  "*" = 2,
  "/" = 2,
  "^" = 2,
  "(" = 1,
  "%%" = 2,
  "%/%" = 2,
  "if" = 3,
  "!" = 1,
  ">" = 2,
  "<" = 2,
  ">=" = 2,
  "<=" = 2,
  "==" = 2,
  "!=" = 2,
  "&&" = 2,
  "||" = 2,
  length = 1,
  nrow = 1,
  ncol = 1,
  sum = 1,
  prod = 1,
  min = 1:2,
  max = 1:2,
  as.logical = 1,
  as.integer = 1,
  as.numeric = 1,
  ceiling = ceiling,
  sign = sign,
  floor = floor,
  round = function(x) NULL, # no digits support yet
  trunc = function(x) NULL,
  sqrt = sqrt,
  abs = abs,
  exp = exp,
  expm1 = expm1,
  log = function(x) NULL, # no general base yet
  log2 = log2,
  log10 = log10,
  log1p = log1p,
  cos = cos,
  sin = sin,
  tan = tan,
  acos = acos,
  asin = asin,
  atan = atan,
  atan2 = atan2,
  cosh = cosh,
  sinh = sinh,
  tanh = tanh,
  acosh = acosh,
  asinh = asinh,
  atanh = atanh)


## TODO: rlang struggles with matching primitives in
## parse_expr_usage/match_call, so we just squash them manually; later
## we'll work out how to cope with this properly.
FUNCTIONS <- lapply(FUNCTIONS, function(x) {
  if (is.primitive(x)) length(formals(args(x))) else x
})

## https://en.cppreference.com/w/cpp/keyword
RESERVED_CPP <- c(
  "alignas",
  "alignof",
  "and",
  "and_eq",
  "asm",
  "atomic_cancel",
  "atomic_commit",
  "atomic_noexcept",
  "auto",
  "bitand",
  "bitor",
  "bool",
  "break",
  "case",
  "catch",
  "char",
  "char8_t",
  "char16_t",
  "char32_t",
  "class",
  "compl",
  "concept",
  "const",
  "consteval",
  "constexpr",
  "constinit",
  "const_cast",
  "continue",
  "co_await",
  "co_return",
  "co_yield",
  "decltype",
  "default",
  "delete",
  "do",
  "double",
  "dynamic_cast",
  "else",
  "enum",
  "explicit",
  "export",
  "extern",
  "false",
  "float",
  "for",
  "friend",
  "goto",
  "if",
  "inline",
  "int",
  "long",
  "mutable",
  "namespace",
  "new",
  "noexcept",
  "not",
  "not_eq",
  "nullptr",
  "operator",
  "or",
  "or_eq",
  "private",
  "protected",
  "public",
  "reflexpr",
  "register",
  "reinterpret_cast",
  "requires",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "static_assert",
  "static_cast",
  "struct",
  "switch",
  "synchronized",
  "template",
  "this",
  "thread_local",
  "throw",
  "true",
  "try",
  "typedef",
  "typeid",
  "typename",
  "union",
  "unsigned",
  "using",
  "virtual",
  "void",
  "volatile",
  "wchar_t",
  "while",
  "xor",
  "xor_eq",
  ## Additional keyword, from http://en.cppreference.com/w/c/keyword -
  ## no longer a C++ keyword apparently, but seems worth excluding
  ## too.
  "restrict")

## https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words
RESERVED_JS <- c(
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "return",
  "static",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield")

SPECIAL_LHS <- c("initial", "update", "deriv", "dim", "config", "output")
SPECIAL_RHS <- c("parameter", "data", "interpolate", "delay")

RESERVED_ODIN <- c(
  "time", "dt", INDEX,
  SPECIAL_LHS, SPECIAL_RHS,
  ## These ones are implementation details and could be relaxed:
  "state", "state_next", "state_deriv", "shared", "internal")

RESERVED <- sort(unique(c(RESERVED_ODIN, RESERVED_CPP, RESERVED_JS)))

RESERVED_ODIN_PREFIX <- c("odin", "interpolate", "delay", "adjoint")
RESERVED_ODIN_PREFIX_RE <- sprintf("^(%s)_.*",
                                   paste(RESERVED_ODIN_PREFIX, collapse = "|"))

PHASES_BROWSER <- c("update", "deriv")
