# Standalone file: do not edit by hand
# Source: https://github.com/reside-ic/reside.utils/blob/mrc-5766/R/standalone-error-render.R
# Generated by: usethis::use_standalone("reside-ic/reside.utils", "error-render", ref = "mrc-5766")
# ----------------------------------------------------------------------
#
# ---
# repo: reside/reside.utils
# file: standalone-errors-render.R
# dependencies: standalone-utils-assert.R
# imports: cli
# ---
error_explain <- function(errors, code, how, call = parent.frame()) {
  assert_scalar_character(code, name = "code", call = call)
  how <- match_value(how, c("pretty", "plain", "link"),
                     name = "how", call = call)

  if (!grepl(errors$pattern$complete, code)) {
    cli::cli_abort(
      "Invalid code '{code}', should match '{errors$pattern$hint}'",
      arg = "code", call = call)
  }
  err <- errors$errors[[code]]
  if (is.null(err)) {
    cli::cli_abort(
      c("Error '{code}' is undocumented",
        i = paste("If you were directed here from an error message, please",
                  "let us know (e.g., file an issue or send us a message)")),
      arg = "code", call = call)
  }
  if (how == "link") {
    url <- sprintf("%s#%s",errors$url, tolower(code))
    utils::browseURL(url)
  } else {
    error_render(err, how == "pretty")
  }
}


error_render <- function(err, pretty) {
  render_paragraph <- function(el) {
    cli::cli_par()
    cli::cli_text(el$text)
  }

  render_code_block <- function(el) {
    cli::cli_par()
    cli::cli_code(paste0("    ", el$text))
  }

  render_list <- function(el) {
    cli::cli_par()
    if (el$mode == "bullet") {
      cli::cli_ul()
    } else {
      cli::cli_ol()
    }
    for (i in el$items) {
      cli::cli_li(i$text)
    }
  }

  if (pretty) {
    cli::cli_h1(err$code)
    for (el in err$parsed) {
      switch(
        el$type,
        paragraph = render_paragraph(el),
        code_block = render_code_block(el),
        list = render_list(el),
        cli::cli_abort("Unknown error block type '{el$type}' while rendering"))
    }
  } else {
    writeLines(c(sprintf("# %s", err$code), "", err$plain))
  }
}
